apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - excalidraw-deployment.yaml
  - excalidraw-service.yaml
  - middleware.yaml
  - ingress.yaml
  - room-deployment.yaml
  - room-service.yaml
