apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: authentik-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: authentik
