apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

labels:
  - pairs:
      app: postgres

resources:
  - serviceaccount.yaml
  - statefulset.yaml
  - service.yaml
  - secretstore.yaml
  - externalsecret.yaml
